name: "Cache/Install NodeJS Dependencies"
description: "Cache dependencies or install them"
author: "LuisFuentech"
branding:
  icon: "save"
  color: "blue"
inputs:
  caching:
    description: "Whether to cache dependencies or not"
    required: false
    default: "true"
  node-manager:
    description: "The node manager to use (npm or yarn)"
    required: false
    default: "npm"
  lock-file:
    description: "The lock file to use"
    required: false
    default: "package-lock.json"
outputs:
  used-cache:
    description: "Whether the cache was used or not."
    value: ${{ steps.set-output.outputs.cache }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v4.2.1
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles(format('**/{0}', inputs.lock-file)) }}
    - name: Install dependencies
      id: install
      if: ${{ inputs.caching == 'true' && steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true' }}
      run: |
        chmod +x $INSTALL_SH
        $INSTALL_SH ${{ inputs.node-manager }} ${{ inputs.lock-file }}
      shell: bash
      env:
        INSTALL_SH: ${{ github.action_path }}/install.sh
    - name: Set Output
      id: set-output
      run: echo "cache='${{ steps.cache.outputs.cache-hit }}'" >> $GITHUB_OUTPUT
      shell: bash
    - name: Print Output
      run: echo "${{ steps.cache.outputs.cache-hit != 'true' && 'Cache was not used' || 'Cache was used' }}"
      shell: bash
